/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  tkoh: [
    /*{
      type: 'category',
      label: '環驅之鑰',
      link: { type: 'doc', id: 'the-key-of-huanche/index' },
      items: [
        'the-key-of-huanche/bnn/index',
        'the-key-of-huanche/primordial-soup/index'
      ],
    },/** */
    'the-key-of-huanche/index',
    {
      type: 'category',
      label: 'Primordial Soup',
      link: { type: 'doc', id: 'the-key-of-huanche/primordial-soup/index' },
      items: [
        'the-key-of-huanche/primordial-soup/bnn/index',
        'the-key-of-huanche/primordial-soup/bnn-tools/index',
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
